### ISSUE TITLE
How to fix Expected a value of type 'FirebaseError', but got one of type 'DomException' in Flutter web setting up push notifications?

### ISSUE THREAD

**Issue by sarohabhawna** [FirebaseExtended/firebase-dart#318]
Dart version: 2.9.0 
OS: Ubuntu 18.04
Firebase package version: 7.3.0

I'm trying to set up firebase notifications in flutter web. I was able to do the basic set up. But when a user clicks allow to give permissions, I'm getting this error.

```
Error: Expected a value of type 'FirebaseError', but got one of type 'DomException'
    at Object.throw_ [as throw] (http://localhost:44987/dart_sdk.js:4461:11)
    at Object.castError (http://localhost:44987/dart_sdk.js:4432:15)
    at Object.cast [as as] (http://localhost:44987/dart_sdk.js:4748:17)
    at dart.AnonymousJSType.new.as (http://localhost:44987/dart_sdk.js:6186:64)
    at handleThenable (http://localhost:44987/packages/firebase/src/storage.dart.lib.js:3264:96)
    at handleThenable.throw (<anonymous>)
    at http://localhost:44987/dart_sdk.js:36909:38
    at _RootZone.runBinary (http://localhost:44987/dart_sdk.js:36762:58)
    at _FutureListener.thenAwait.handleError (http://localhost:44987/dart_sdk.js:31933:48)
    at handleError (http://localhost:44987/dart_sdk.js:32475:51)
    at Function._propagateToListeners (http://localhost:44987/dart_sdk.js:32498:17)
    at _Future.new.[_completeError] (http://localhost:44987/dart_sdk.js:32354:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:44987/dart_sdk.js:32392:31)
    at Object._microtaskLoop (http://localhost:44987/dart_sdk.js:37015:13)
    at _startMicrotaskLoop (http://localhost:44987/dart_sdk.js:37021:13)
```

This is my `index.html` file

```
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="Lorem ipsum">
  <meta name="robots" content="noindex">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Flutter web notifications">
  <meta id="flutterweb-theme" name="theme-color" content="#393557">
  <link rel="icon" type="image/png" href="/icons/Icon-192.png">
  <link rel="apple-touch-icon" href="/icons/Icon-192.png">

  <title>Flutter web notifications</title>
  <link rel="manifest" href="./manifest.json">
</head>

<body id="app-container">
  <!-- This script installs service_worker.js to provide PWA functionality to
      application. For more information, see:
      https://developers.google.com/web/fundamentals/primers/service-workers -->

  <script src="https://www.gstatic.com/firebasejs/7.9.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.9.1/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.9.1/firebase-firestore.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.9.1/firebase-messaging.js"></script>
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function () {
        // navigator.serviceWorker.register('/flutter_service_worker.js');
        navigator.serviceWorker.register("./firebase-messaging-sw.js");
      });
    }
  </script>
  <script src="https://www.gstatic.com/firebasejs/7.11.0/firebase-analytics.js"></script>
  <script>
    // Your web app's Firebase configuration
    var firebaseConfig = {
      apiKey: "API_KEY",
      authDomain: "AUTH_DOMAIN",
      databaseURL: "DATABASE_URL",
      projectId: "PROJECT_ID",
      storageBucket: "STORAGE_BUCKET",
      messagingSenderId: "MESSAGING_SENDER_ID",
      appId: "APP_ID",
      measurementId: "MEASUREMENT_ID"
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
    firebase.analytics();
  </script>

  <!-- <script src="/__/firebase/init.js"></script> -->
  <script src="main.dart.js" type="application/javascript"></script>
</body>

</html>
```

This is the `firebase-messaging-sw.js` service worker file

```
importScripts("https://www.gstatic.com/firebasejs/7.9.1/firebase-app.js");
importScripts("https://www.gstatic.com/firebasejs/7.9.1/firebase-messaging.js");
var firebaseConfig = {
  apiKey: "API_KEY",
  authDomain: "AUTH_DOMAIN",
  databaseURL: "DATABASE_URL",
  projectId: "PROJECT_ID",
  storageBucket: "STORAGE_BUCKET",
  messagingSenderId: "MESSAGING_SENDER_ID",
  appId: "APP_ID",
  measurementId: "MEASUREMENT_ID"
};
firebase.initializeApp(firebaseConfig);
// firebase.analytics();
const messaging = firebase.messaging();
messaging.setBackgroundMessageHandler(function (payload) {
  const promiseChain = clients
    .matchAll({
      type: "window",
      includeUncontrolled: true
    })
    .then(windowClients => {
      for (let i = 0; i < windowClients.length; i++) {
        const windowClient = windowClients[i];
        windowClient.postMessage(payload);
      }
    })
    .then(() => {
      return registration.showNotification("New Message");
    });
  return promiseChain;
});
self.addEventListener('notificationclick', function (event) {
  console.log('notification received: ', event)
});
```

This is the `firebase_messaging.dart`

```
import 'dart:async';
import 'package:firebase/firebase.dart' as firebase;

class FBMessaging {
  FBMessaging._();
  static FBMessaging _instance = FBMessaging._();
  static FBMessaging get instance => _instance;
  // firebase.Messaging _mc;
  var _mc;
  String _token;

  final _controller = StreamController<Map<String, dynamic>>.broadcast();
  Stream<Map<String, dynamic>> get stream => _controller.stream;

  void close() {
    _controller?.close();
  }

  Future<void> init() async {
    _mc = firebase.messaging();
    _mc.usePublicVapidKey('FCM_SERVER_KEY');
    _mc.onMessage.listen((event) {
      _controller.add(event?.data);
    });
  }

  Future requestPermission() {
    // await init();
    return _mc.requestPermission();
  }

  Future<String> getToken([bool force = false]) async {
    if (force || _token == null) {
      // await requestPermission();
      _token = await _mc.getToken();
    }
    return _token;
  }
}
```
This is how I'm requesting permissions from the user

```
final _messaging = FBMessaging.instance;
() async {
  _messaging
   .init()
    .then((_) async {
     await _messaging
     .requestPermission()
     .then((_) async {
   final _token =
     await _messaging
     .getToken();
     print('Token: $_token');
    });
  });
}
```
I can't seem to find that what could be the cause of this error.

**Comment by sam-parks** [comment]
I'm getting this same error as well with pretty much the same code.

Firebase package version: 7.14.6

**Comment by mordivgor** [comment]
Unfortunately, same here.
Version 7.3.0.

**Comment by vitoramerico** [comment]
Version 7.5.0 worked for me

**Comment by mordivgor** [comment]
@vitoramerico how it is possible as the newest version is only 7.3.0? ;)

**Comment by vitoramerico** [comment]
> @vitoramerico how it is possible as the newest version is only 7.3.0? ;)

This version worked for me
  <script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-firestore.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-messaging.js"></script>

**Comment by kevmoo** [comment]
What @vitoramerico said!

I've updated the documented/tested version at https://github.com/FirebaseExtended/firebase-dart/commit/209cf2c1a54b61dae27a8847a5805aa9c61b0e75
