### ISSUE TITLE
dart.global.firebase.storage is not a function

### ISSUE THREAD

**Issue by sumitsingh1698** [FirebaseExtended/firebase-dart#331]
I am trying to upload file in firebase storage from flutter web.
`
    Future<Uri> uploadImageFile(html.File image, {String imageName}) async {
   
    fb.StorageReference storageRef = fb.storage().ref('images/aa');
    fb.UploadTaskSnapshot uploadTaskSnapshot =
        await storageRef.put(image).future;

    Uri imageUri = await uploadTaskSnapshot.ref.getDownloadURL();
    return imageUri;
  }`

 This throwing a error : 

> TypeError: dart.global.firebase.storage is not a function
    at Object.storage$ [as storage] (http://localhost:33391/packages/firebase/src/top_level.dart.lib.js:90:100)
    at uploadImageFile (http://localhost:33391/packages/adminpanel/models/user_repository.dart.lib.js:95:33)
    at uploadImageFile.next (<anonymous>)
    at runBody (http://localhost:33391/dart_sdk.js:37231:34)
    at Object._async [as async] (http://localhost:33391/dart_sdk.js:37262:7)
    at user_repository.UserRepository.new.uploadImageFile (http://localhost:33391/packages/adminpanel/models/user_repository.dart.lib.js:94:20)
    at user_repository.UserRepository.new.<anonymous> (http://localhost:33391/packages/adminpanel/models/user_repository.dart.lib.js:87:18)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:33391/dart_sdk.js:37231:34)
    at Object._async [as async] (http://localhost:33391/dart_sdk.js:37262:7)
    at http://localhost:33391/packages/adminpanel/models/user_repository.dart.lib.js:86:67
    at Object._checkAndCall (http://localhost:33391/dart_sdk.js:4532:16)
    at Object.dcall (http://localhost:33391/dart_sdk.js:4537:17)
    at FileReader.<anonymous> (http://localhost:33391/dart_sdk.js:104668:21)

**Comment by sumitsingh1698** [comment]
I find out why this was coming

**Comment by sobhan15** [comment]
> I find out why this was coming

### **You have helped a lot if you tell us how to solve the problem**
