### ISSUE TITLE
No Firebase App '[DEFAULT]' has been created

### ISSUE THREAD

**Issue by praharshbhatt** [FirebaseExtended/firebase-dart#332]
After upgrading all the firebase libs, I get the following error:

```
E/flutter (30774): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
E/flutter (30774): #0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:118:5)
E/flutter (30774): #1      Firebase.app (package:firebase_core/src/firebase.dart:52:41)
E/flutter (30774): #2      FirebaseAuth.instance (package:firebase_auth/src/firebase_auth.dart:37:47)
E/flutter (30774): #3      AuthService.checkIsSignedIn (package:gujarat_advocates_lawyer/services/auth.dart:27:22)
E/flutter (30774): #4      AuthService.login (package:gujarat_advocates_lawyer/services/auth.dart:15:15)
E/flutter (30774): #5      authenticateUser (package:gujarat_advocates_lawyer/screens/splashscreen.dart:76:30)
E/flutter (30774): #6      SplashState.initState (package:gujarat_advocates_lawyer/screens/splashscreen.dart:31:5)
E/flutter (30774): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
E/flutter (30774): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (30774): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30774): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30774): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30774): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30774): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30774): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (30774): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (30774): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter (30774): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (30774): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30774): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30774): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30774): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30774): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30774): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30774): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30774): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30774): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (30774): #27     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
E/flutter (30774): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (30774): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter (30774): #30     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
E/flutter (30774): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (30774): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30774): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30774): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30774): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30774): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30774): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30774): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30774): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30774): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (30774): #41     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
E/flutter (30774): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (30774): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter (30774): #44     StatefulElement._firstBuild (package:flutter/src/widg
```

Firebase packages:
```
  firebase_analytics: ^6.0.0
  cloud_firestore: ^0.14.0
  firebase_messaging: ^7.0.0
  firebase_auth: ^0.18.0
  firebase_storage: ^4.0.0
```

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!
```

**Comment by MinhMinh9201** [comment]
Hey guy, i think this case it you have initialize app two time, can you show me here code?

**Comment by praharshbhatt** [comment]
just had to initialize the app, then it works-

```
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
```

in main()
