### ISSUE TITLE
 TypeError: dart.global.firebase.firestore is not a function  How to resolve it.?

### ISSUE THREAD

**Issue by Dinesh130914** [FirebaseExtended/firebase-dart#398]
TypeError: dart.global.firebase.firestore is not a function
    at Object.firestore$ [as firestore] (http://localhost:57305/packages/firebase/src/top_level.dart.lib.js:99:55)
    at new cloud_firestore_web.FirestoreWeb.new (http://localhost:57305/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:806:37)
    at Function.registerWith (http://localhost:57305/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:751:71)
    at Object.registerPlugins (http://localhost:57305/packages/Medcell/generated_plugin_registrant.dart.lib.js:19:38)
    at main (http://localhost:57305/web_entrypoint.dart.lib.js:34:35)
    at main.next (<anonymous>)
    at runBody (http://localhost:57305/dart_sdk.js:39819:34)
    at Object._async [as async] (http://localhost:57305/dart_sdk.js:39850:7)
    at main$ (http://localhost:57305/web_entrypoint.dart.lib.js:33:18)
    at http://localhost:57305/main_module.bootstrap.js:19:10
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (http://localhost:57305/main_module.bootstrap.js:18:32)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:57305/dwds/src/injected/client.js:9024:21)
    at http://localhost:57305/dwds/src/injected/client.js:23836:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:57305/dwds/src/injected/client.js:3915:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:57305/dwds/src/injected/client.js:11461:12)
    at Object._asyncStartSync (http://localhost:57305/dwds/src/injected/client.js:3879:20)
    at main__closure3.$call$body$main__closure (http://localhost:57305/dwds/src/injected/client.js:23848:16)
    at main__closure3.call$1 (http://localhost:57305/dwds/src/injected/client.js:23775:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:57305/dwds/src/injected/client.js:4273:18)
    at _CustomZone.runUnary$2$2 (http://localhost:57305/dwds/src/injected/client.js:12833:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:57305/dwds/src/injected/client.js:12776:14)
    at _ForwardingStreamSubscription._sendData$1 (http://localhost:57305/dwds/src/injected/client.js:12373:19)
    at _ForwardingStreamSubscription._add$1 (http://localhost:57305/dwds/src/injected/client.js:12319:15)
    at _ForwardingStreamSubscription._add$1 (http://localhost:57305/dwds/src/injected/client.js:12666:12)
    at _MapStream._handleData$2 (http://localhost:57305/dwds/src/injected/client.js:12727:12)
    at _ForwardingStreamSubscription._handleData$1 (http://localhost:57305/dwds/src/injected/client.js:12692:20)
    at Object.eval (eval at Closure_forwardCallTo (http://localhost:57305/dwds/src/injected/client.js:1427:14), <anonymous>:3:40)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:57305/dwds/src/injected/client.js:4273:18)
    at _CustomZone.runUnary$2$2 (http://localhost:57305/dwds/src/injected/client.js:12833:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:57305/dwds/src/injected/client.js:12776:14)
    at _ControllerSubscription._sendData$1 (http://localhost:57305/dwds/src/injected/client.js:12373:19)
    at _ControllerSubscription._add$1 (http://localhost:57305/dwds/src/injected/client.js:12319:15)
    at _SyncStreamController._sendData$1 (http://localhost:57305/dwds/src/injected/client.js:12158:32)
    at _SyncStreamController.add$1 (http://localhost:57305/dwds/src/injected/client.js:12037:15)
    at Object.eval (eval at Closure_forwardInterceptedCallTo (http://localhost:57305/dwds/src/injected/client.js:1510:14), <anonymous>:3:38)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:57305/dwds/src/injected/client.js:4273:18)
    at _CustomZone.runUnary$2$2 (http://localhost:57305/dwds/src/injected/client.js:12833:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:57305/dwds/src/injected/client.js:12776:14)
    at _ControllerSubscription._sendData$1 (http://localhost:57305/dwds/src/injected/client.js:12373:19)
    at _ControllerSubscription._add$1 (http://localhost:57305/dwds/src/injected/client.js:12319:15)
    at _SyncStreamController._sendData$1 (http://localhost:57305/dwds/src/injected/client.js:12158:32)
    at _SyncStreamController.add$1 (http://localhost:57305/dwds/src/injected/client.js:12037:15)
    at _GuaranteeSink.add$1 (http://localhost:57305/dwds/src/injected/client.js:23277:25)
    at HtmlWebSocketChannel_closure1.call$1 (http://localhost:57305/dwds/src/injected/client.js:23570:61)
    at _EventStreamSubscription_closure.call$1 (http://localhost:57305/dwds/src/injected/client.js:17887:26)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:57305/dwds/src/injected/client.js:4279:16)
    at _CustomZone.runUnary$2$2 (http://localhost:57305/dwds/src/injected/client.js:12833:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:57305/dwds/src/injected/client.js:12776:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://localhost:57305/dwds/src/injected/client.js:12969:25)
    at invokeClosure (http://localhost:57305/dwds/src/injected/client.js:1260:26)
    at WebSocket.<anonymous> (http://localhost:57305/dwds/src/injected/client.js:1279:18)

**Comment by kevmoo** [comment]
Guessing you are not including the required JS library in your html
